# Generated by Django 3.2.4 on 2021-06-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210628_0847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='faculty',
        ),
    ]
